name: Waka Readme Stats

on:
  schedule:
    - cron: "0 * * * *"  # Every hour at minute 0 (i.e., 12:00 AM, 1:00 AM, ..., 11:00 PM UTC)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: WakaTime Stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # ✅ Disable all the unwanted sections
          SHOW_PROFILE_VIEWS: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "True"
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "False"

          # Timeline chart OFF
          SYMBOL_VERSION: "1"

          COMMIT_MESSAGE: "📊 Update WakaTime stats"
          COMMIT_USERNAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
