name: Waka Readme Stats

on:
  schedule:
    - cron: "0 18 * * *"  # runs every day at 11:30 PM IST
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: WakaTime Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PULL_BRANCH_NAME: "main"
          PUSH_BRANCH_NAME: "main"
          SHOW_PROFILE_VIEWS: "False"
